export { default as App } from "./App"
export { default as MainPage } from "./MainPage"
export { default as ArticlePage } from "./ArticlePage"
export { default as NewsPage } from "./NewsPage"
export { default as ServicesPage } from "./ServicesPage"
export { default as GalleryPage } from "./GalleryPage"
export { default as NewspaperPage } from "./NewspaperPage"
