export { default as Header } from "./Header"
export { default as LastNewsSlider } from "./LastNewsSlider"
export { default as About } from "./About"
export { default as Contacts } from "./Contacts"
// export { default as Feed } from "./Feed"
export { default as News } from "./News"
export { default as Article } from "./Article"
export { default as ArticleFilter } from "./ArticleFilter"
export { default as NewsFilter } from "./NewsFilter"
export { default as Filter } from "./Filter"
