export { default as Header } from "./Header"
export { default as LastNewsSlider } from "./LastNewsSlider"
export { default as About } from "./About"
export { default as Contacts } from "./Contacts"
export { default as NewsFeed } from "./NewsFeed"
export { default as NewsArray } from "./NewsArray"
export { default as NewsArticle } from "./NewsArticle"
export { default as Filter } from "./Filter"
